name = "gozargah-pages"
compatibility_date = "2025-01-15"
pages_build_output_dir = "dist-pages"

[[d1_databases]]
binding = "GZ_DB"
database_name = "gozargah"
database_id = "e30094a9-9fac-4335-bc3b-4a146a94ba5a"

[ai]
binding = "AI"

[observability]
enabled = true
